# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shaquille625GmailComSBE5I' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shaquille625GmailComSBE5I
  pod 'Alamofire', '~> 4.7'
end
